import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { StatetreeGeneratedModule, StatetreeGeneratedSharedModule } from './generated/module';
import { StatetreeValidator, registerValidationChecks } from './statetree-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type StatetreeAddedServices = {
    validation: {
        StatetreeValidator: StatetreeValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type StatetreeServices = LangiumServices & StatetreeAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const StatetreeModule: Module<StatetreeServices, PartialLangiumServices & StatetreeAddedServices> = {
    validation: {
        StatetreeValidator: () => new StatetreeValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createStatetreeServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Statetree: StatetreeServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        StatetreeGeneratedSharedModule
    );
    const Statetree = inject(
        createDefaultModule({ shared }),
        StatetreeGeneratedModule,
        StatetreeModule
    );
    shared.ServiceRegistry.register(Statetree);
    registerValidationChecks(Statetree);
    return { shared, Statetree };
}
